### ISSUE TITLE
No longer able to get firmware output

### ISSUE THREAD

**Issue by vixadd** [MotorolaMobilityLLC/nuttx#59]
The `nuttx.bin` `nuttx.hex` and `nuttx.tftf` files are no longer being outputted.
Running in ubuntu 16.10, when I call the following:
```bash
$ cd ./nuttx/nuttx
$ make distclean
$ cd ./tools
$ ./configure.sh hdk/muc/base_unpowered
$ cd ..
$ make
```
I get the following output.

Just want some help.
```
CC:  exec_builtin.c
exec_builtin.c: In function 'exec_builtin':
exec_builtin.c:232:16: error: the address of 'attr' will always evaluate as 'true' [-Werror=address]
   (void)posix_spawnattr_destroy(&attr);
                ^
exec_builtin.c:239:16: error: the address of 'attr' will always evaluate as 'true' [-Werror=address]
   (void)posix_spawnattr_destroy(&attr);
                ^
cc1: all warnings being treated as errors
Makefile:101: recipe for target 'exec_builtin.o' failed
make[2]: *** [exec_builtin.o] Error 1
Makefile:155: recipe for target 'builtin_all' failed
make[1]: *** [builtin_all] Error 2
LibTargets.mk:157: recipe for target '../apps/libapps.a' failed
make: *** [../apps/libapps.a] Error 2
```

**Comment by flowflow25** [comment]
We aren't currently 16.10 based, so this solution has not been tested.
There are two solutions:
1. Remove -Werror from the Makefile.  This flag causes all warnings to be treated as errors.
2. In spawn.h:
/* int posix_spawnattr_destroy(FAR posix_spawnattr_t *); */
#ifdef CONFIG_DEBUG
**#pragma GCC diagnostic push
#pragma GCC ignored "-Waddress"**
#define posix_spawnattr_destroy(attr) (attr ? 0 : EINVAL)
**#pragma GCC diagnostic pop**
#else
#define posix_spawnattr_destroy(attr) (0)
#endif

We will push solution #2 once we're able to validate it works properly.  But we did not want to continue blocking you.

**Comment by vixadd** [comment]
Thank you so much. I can help test solution 2, and tell you the results, but if you have specific unit tests you follow for integration, I'd rather leave it up to you.

**Comment by flowflow25** [comment]
If you could give us your specific arm-none-eabi-gcc version, that would be helpful to make sure we're all on the same page.

**Comment by vixadd** [comment]
```bash
$ arm-none-eabi-gcc --version

arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by vixadd** [comment]
I believe that's version 4.9.3

**Comment by vixadd** [comment]
For the record, I am attempting this project: 
[Blinky MotoMod](https://www.element14.com/community/groups/moto-mods/blog/2017/04/22/moto-mods-developer-part-1-getting-started-virtual-machine-setup-and-linux-install)

I am getting stuck on part 4 where firmware output is required to progress.

**Comment by vixadd** [comment]
solution 2 seems to give me the same error.

**Comment by vixadd** [comment]
![screenshot from 2017-12-07 02-56-50](https://user-images.githubusercontent.com/9141655/33704420-65f6f486-dafa-11e7-8540-aefaf9a471b1.png)
![screenshot from 2017-12-07 02-57-16](https://user-images.githubusercontent.com/9141655/33704422-66089c22-dafa-11e7-8920-f64913ce961a.png)

**Comment by jwylder1** [comment]
I just did a clean install of Ubuntu 16.10, setup the repos and it built cleanly (without the patch).  Something in your setup/environment is not matching the standard setup.

Did you try option 1:  edit Make.defs to change the 
`ARCHCFLAGS = -fno-builtin -Werror -Wno-cpp -fno-short-enums`
to read 
`ARCHCFLAGS = -fno-builtin -Wno-cpp -fno-short-enums`

If this still fails also run
make -n to verify that the compile command does not have the -Werror in it

**Comment by vixadd** [comment]
Hey,

Sorry for not getting back to you, but I've been working on projects all vacation. I forgot to tell you that I solved the problem. Turns out that a fresh ubuntu install helped. Don't know what the problem was, but I wanted to thank you guys for responding so quick.

All the best,
Closing this now.

**Comment by jwylder1** [comment]
Thanks good to know.

**Comment by vixadd** [comment]
I'm sorry to write here again.

But I was wondering if I could get some advice from the engineers for this. I am trying to build an FM Transmitter for my phone's audio. I've built a GPIO FM transmitter in the past on a raspberry Pi, but I was wondering how I could implement this on my phone's mod. I have a Moto Z Play. I'm still navigating my way around some of the firmware, and I've only done one simple project. Is there any way in particular that I can go about this? I'm a student at a University also.

**Comment by flowflow25** [comment]
Please use our [element14 forums](https://www.element14.com/community/groups/moto-mods
) for these questions, as it will benefit our entire community.
If you have private questions, mdk-help@motorola.com is the best spot.

In the meantime, have you had a chance to check out the [Audio Example](https://developer.motorola.com/build/examples/audio)?  Seems like this is a good start, you'll just need to route it to your transmitter then add in some control of that.
