### ISSUE TITLE
FM Transmitter

### ISSUE THREAD

**Issue by vixadd** [MotorolaMobilityLLC/nuttx#62]
Hello,
I went to post on the element14 group, and I haven't received an answer. So I will post the answer to the thread there.
I am making an FM Transmitter for my phone, and actually making a Moto Mod for it. Right now, I have two modules from Adafruit that I am using. A Stereo Decoder, (UDA1334A - https://www.adafruit.com/product/3678) and an FM Transmitter. (Si4713 - https://learn.adafruit.com/adafruit-si4713-fm-radio-transmitter-with-rds-rdbs-support/overview) The whole notion behind the design, is that I take the Left out and the Right out from the stereo decoder, and I take them to the FM Transmitter.

![image](https://user-images.githubusercontent.com/9141655/38166050-32d38ca4-34eb-11e8-9d5d-4b116510ee59.png)

My question is: What would the best way be to go about writing the firmware for this application? I've looked into a lot of the audio stuff for the MDK. I've looked through the Audio Protocol section, and read through a little bit of the TFA9882 stuff to get an idea of how to control audio. Also, if the design is not feasible, or it's not good, please let me know.

Please excuse my horrible soldering skills. the test points are very small, I don't have a microscope, but to have a shaky hand.

![image](https://user-images.githubusercontent.com/9141655/38166200-ca477a08-34ed-11e8-98c2-3c8f331ecd08.png)

**Comment by jwylder1** [comment]
Your project appears to have two components:

1) Audio interface to the phone.  You are generally looking at the right stuff, this is similar to the speaker example.  But you don't need to worry about the TFA code.  I could be wrong but it looks like the Adafruit part doesn't need all the dsp software loading etc.  You would just need to give it power and then implement the greybus part that tells the phone to start sending audio to the mod.

You should probably just get this working through the headset first.  It is actually a useful mod on its own.

2) Once you have working audio, the FM transmitter control will have to be RAW interface.  So there is a android app that you can send messages about frequencies that would end up probably being sent over the i2c driver.  There are lots of examples of I2C drivers.

**Comment by vixadd** [comment]
Okay. I think I see what you're saying. I'll see if I can follow the
greybus setup on the audio protocol on the developer website. The
MDKUtility app isn't compiling properly. So I need to get that working
since I can't successfully deploy mods on the app available on the app
store due to the set modes option that backs out of developer mode every
time.

I'll be back with an update once I get the MDK Utility open.

**Comment by vixadd** [comment]
So, just as an update for you, I forgot to include the moto mods library that you have to import into android studio. It's why it wasn't working.

I am having trouble figuring out which NuttX menuconfig stuff needs to be in the configuration for NuttX.  However, the TFA configuration stuff helped me out a little bit. But I agree, I guess the best way is to just connecting the headset to the UDA1334 itself. I added I2C support stuff in Device Drivers in the menu config, and added my own branch for the project.

Oh by the way, everything is in this repository: https://github.com/vixadd/FMoto.git
The Hardware manifest:
https://github.com/vixadd/FMoto/blob/master/nuttx/apps/greybus-utils/manifests/hdk-fmoto.mnfs

FM Transmitter Configs:
https://github.com/vixadd/FMoto/tree/master/nuttx/nuttx/configs/hdk/muc/fm_xmitter

I'm going to read through a few things tonight, and see if I can understand some of the I2C stuff.
I found this as a resource yesterday. Maybe I can draw a few things from it. If I can get this working and display it for my class, it'd be awesome.

https://github.com/akhilnarang/kernel_bullhead/blob/master/drivers/media/radio/si4713-i2c.c

**Comment by vixadd** [comment]
Also, the main code to write all the I2C stuff in. Is it in the modsraw file?
I'll figure out the code if I know where it goes and how to reference it properly in the makefile.
https://github.com/MotorolaMobilityLLC/nuttx/blob/master/nuttx/configs/hdk/muc/src/stm32_modsraw.c

I know that there's some sort of Variable name that needs to be created so that the makefile points to the right program. I hope I'm on the right track.
https://github.com/MotorolaMobilityLLC/nuttx/blob/master/nuttx/configs/hdk/muc/src/Makefile

**Comment by vixadd** [comment]
So, quick update:
- I have the MDK Utility app working where I can successfully deploy the application. 
- NuttX runs fine for now, but I need to know where I should actually write the I2C stuff so I can start controlling the audio. I copied all of the files for the I2S stuff from the Speaker mod, I think I need to set some variables differently, but until then, I think I can try to figure out what's going on in the code to get the audio out of the phone.
- Would it be better to start with base_unpowered instead of speaker? I think this might be more suited to the whole going from the headphone jack to the stereo decoder.

Next step is to set everything up on a breadboard and get stuff working through the HAT adapter.

Any thoughts?

**Comment by jwylder1** [comment]
There really is no rule about where you have to put your I2C code.  Nuttx
has one large memory space so most things will work.  We had a pattern we
tried to follow to split things out so that people could build on the
code.  Not sure we were always successful.

I would recommend at this stage just put the code anywhere that works for
you.  After everything works you can always clean stuff up later.

What to start with is your choice.  Either way will work.

Jim

**Comment by vixadd** [comment]
Okay. Yeah, Looking over the stm32_audio_tfa9880.c I can see some I2C stuff going on. I guess if I just make backups of the original tfa code and then put the I2C stuff I need in there, I can get some sort of signal out of the circuit. ;)

I know all of this really makes me and it sound dumb, but I am super interested in this platform. I will continue looking into it into the summer and possibly do more cool things with it. I'm demonstrating my progress in this whole thing next week for an open source club on campus here. I think they will be interested in it as well.

**Comment by vixadd** [comment]
Just one last question: I am having trouble flashing the firmware. The nuttx.tftf software to the board when I compile the hdk/muc/speaker stuff. Is there something I'm missing. The compilation seems to happen flawlessly:

```
cd nuttx/nuttx/
make distclean
cd tools/
./configure.sh hdk/muc/speaker
cd ..
make
#   And the nuttx.tftf file is created.
```

When I try to put this on my phone and try to flash it in developer mode, I get a Firmware update Error - EINVAL.
Is there something that I'm doing wrong?

**Comment by vixadd** [comment]
Also, again, thank you for responding to so many questions. I know you guys are busy, and the last thing you need is a guy who's breaking everything.

**Comment by jwylder1** [comment]
​I will try to help as much as I can but I haven't worked on Mods for a
couple of years and I might have used the application to flash in running a
few test cases but never in my main work flow.  I do remember that you need
to make sure that you have put the device in developer mode.

If you are doing anything on the Mods I recommend using Open OCD to flash.
Once you have this setup you will also have a debugger.  It is more
complicated to get started but is faster, more reliable and you will end up
needing that debugger at some point.  The instructions for setting up the
tools are https://developer.motorola.com/documentation/setup-environment.

Good Luck

Jim

**Comment by vixadd** [comment]
Just to close this thread out. I had the full presentation today, and it was an overall success. Thank you for your help. I hope to continue working with NuttX and the Motorola Moto Mods platform. I think this is will be an excellent source of innovation.

![image](https://user-images.githubusercontent.com/9141655/39077387-7494ab3e-44cf-11e8-8bf5-a2783f66e087.png)
![image](https://user-images.githubusercontent.com/9141655/39077390-7a2b5a52-44cf-11e8-8e78-d7fc5425875e.png)

What the pictures don't show is that I was actually able to get the I2C drivers working on the mod. Once I finish this project, I hope to continue working on different mods.

Thanks again guys!
