### ISSUE TITLE
CONFIG_CHIP_PRODUCT_ID=0x00006435

### ISSUE THREAD

**Issue by rafaelcorsi** [MotorolaMobilityLLC/nuttx#64]
https://github.com/MotorolaMobilityLLC/nuttx/blob/31da121ca38e6d63a4023d3e1a320338839a0f41/nuttx/configs/hdk/muc/speaker/defconfig#L34

Why this example has a different `CONFIG_CHIP_PRODUCT_ID=0x00006435` from others (`CONFIG_CHIP_PRODUCT_ID=0x00006415`) ? 

all the best,

R. Corsi

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested on request, please re-open the issue.
