### ISSUE TITLE
USB3(.0/.1 gen1/2?) doesnt work with MDK-Compute Firmware

### ISSUE THREAD

**Issue by BitWire** [MotorolaMobilityLLC/nuttx#65]
When i try to use the usb3(.0/.1 gen1/2 or what motorola is using) with the reference mod, i cannot make use of it. It just doesn't detect any usb device i plug into it, regardless what usb standard.

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested on request, please re-open the issue.
