### ISSUE TITLE
https://drive.google.com/file/d/0B-VWeWRw2fwpT2Z3Z1Q4Z2UwUnU2N1lVd1NRel92OUVkX0Iw/view?usp=drivesdk

### ISSUE THREAD

**Issue by Miguel19961108** [MotorolaMobilityLLC/nuttx#66]
No tengo señal de red móvil

**Comment by vinimed** [comment]
Hello @Miguel19961108, sorry for late response. Are you still facing the above error?

**Comment by vinimed** [comment]
After a long time without any answer, we are closing the issue. If you are still facing the errors above, please re-open the issue.
Thank you.
